_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
epsilon_decay:
    value: 0.995
epsilon_end:
    value: 0.01
epsilon_start:
    value: 1
eval_episodes:
    value: 10
gamma:
    value: 0.99
grid_size:
    value: 10
learning_rate:
    value: 0.001
load_model:
    value: null
max_steps:
    value: 200
memory_size:
    value: 10000
mode:
    value: train
num_episodes:
    value: 1000
render:
    value: false
render_freq:
    value: 50
save_dir:
    value: models
save_freq:
    value: 100
tether_length:
    value: 3
